name: npm-publish
on:
  push:
    # tags:
    #   - 'v*.*.*'
    branches:
      - main123 # Change this to your default branch
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - run: echo disable
      # - name: Checkout repository
      #   uses: actions/checkout@v4.1.1

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     generate_release_notes: true
      #     make_latest: true

      # - name: Setup node
      #   uses: actions/setup-node@v4.0.2
      #   with:
      #     node-version: '20'
      # - name: Install
      #   run: npm ci

      # - name: Build
      #   run: npm run build

      # - uses: JS-DevTools/npm-publish@v3.0.1
      #   id: util
      #   with:
      #     token: ${{ secrets.NPM_AUTH_TOKEN }}
      #     package: './packages/util'
      #     access: public
      # - run: echo ${{ steps.util.outputs.id }}

      # - uses: JS-DevTools/npm-publish@v3.0.1
      #   id: tools
      #   with:
      #     token: ${{ secrets.NPM_AUTH_TOKEN }}
      #     package: './packages/tools'
      #     access: public
      # - run: echo ${{ steps.tools.outputs.id }}
