name: npm-publish
on:
  push:
    branches:
      - main # Change this to your default branch
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
    - name: Setup node
      uses: actions/setup-node@v4.0.2
      with:
        node-version: "20"
    - name: Install
      run: npm ci

    - uses: JS-DevTools/npm-publish@v3.0.1
      id: eslint
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: "./packages/eslint-config"
        access: public
    - run: echo ${{ steps.eslint.outputs.id }}

    - uses: JS-DevTools/npm-publish@v3.0.1
      id: react
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: "./packages/eslint-config-react"
        access: public
    - run: echo ${{ steps.react.outputs.id }}
    
    - uses: JS-DevTools/npm-publish@v3.0.1
      id: jest
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: "./packages/jest-config"
        access: public
    - run: echo ${{ steps.jest.outputs.id }}

    - uses: JS-DevTools/npm-publish@v3.0.1
      id: prettier
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: "./packages/prettier-config"
        access: public
    - run: echo ${{ steps.prettier.outputs.id }}
    
    - uses: JS-DevTools/npm-publish@v3.0.1
      id: ts
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: "./packages/ts-config"
        access: public
    - run: echo ${{ steps.ts.outputs.id }}

    # - name: Publish if version has been updated
    #   uses: wtrocki/npm-publish-monorepo-action@2.0.0
    #   with: 
    #     workspace: "./packages" # Required
    #     versionFrom: "."
    #     tag_name: "v%s"
    #     tag_message: "v%s"
    #     create_tag: "true"
    #     commit_pattern: "^chore: Release (\\S+)"
    #     publish_args: "--non-interactive --dry-run"
    #   env: # More info about the environment variables in the README
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
